#!/usr/bin/env python3
"""Generate each agent tool's guardrail config from ~/.agents/guardrails.yaml.

Claude Code and OpenCode keep other settings in the same file, so the entries written
here are recorded in guardrails.state.json and only those are replaced on the next run.
Codex gets a rules file of its own. Tools whose config directory does not exist are
skipped.
"""
import json
import os
import shlex
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("sync-guardrails: PyYAML is missing. Run with `uv run --with pyyaml python3 "
             f"{sys.argv[0]}` or install it (Debian/Ubuntu: apt install python3-yaml).")

HOME = Path.home()
POLICY = HOME / ".agents" / "guardrails.yaml"
STATE = HOME / ".agents" / "guardrails.state.json"
CLAUDE_DIR = HOME / ".claude"
CODEX_DIR = Path(os.environ.get("CODEX_HOME", HOME / ".codex"))
OPENCODE_DIR = HOME / ".config" / "opencode"
CLAUDE = CLAUDE_DIR / "settings.json"
CODEX = CODEX_DIR / "rules" / "guardrails.rules"
OPENCODE = OPENCODE_DIR / "opencode.json"


def load_json(path: Path, default: dict) -> dict:
    return json.loads(path.read_text()) if path.exists() else default


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def replace_managed(current: list, previous: list, new: list) -> list:
    return [r for r in current if r not in previous and r not in new] + new


def sync_claude(policy: dict, state: dict) -> None:
    # Claude Code: deny > ask > allow regardless of order.
    new = {
        "deny": [f"Bash({c}{s})" for c in policy["deny"] for s in ("", " *")]
                + [f"Read({p})" for p in policy["deny_read"]],
        "ask": [f"Bash({c}{s})" for c in policy["ask"] for s in ("", " *")],
    }
    settings = load_json(CLAUDE, {})
    permissions = settings.setdefault("permissions", {})
    previous = state.get("claude", {})
    for key, rules in new.items():
        permissions[key] = replace_managed(permissions.get(key, []), previous.get(key, []), rules)
    write_json(CLAUDE, settings)
    state["claude"] = new


def sync_codex(policy: dict) -> None:
    # Codex: the most restrictive matching rule wins (forbidden > prompt > allow).
    lines = ["# Generated by ~/.agents/sync-guardrails.py from ~/.agents/guardrails.yaml. Do not edit."]
    for decision, commands in (("forbidden", policy["deny"]), ("prompt", policy["ask"])):
        for c in commands:
            lines.append(f'prefix_rule(pattern={json.dumps(shlex.split(c))}, decision="{decision}", '
                         f'justification="~/.agents/guardrails.yaml")')
    CODEX.parent.mkdir(parents=True, exist_ok=True)
    CODEX.write_text("\n".join(lines) + "\n")


def sync_opencode(policy: dict, state: dict) -> None:
    # OpenCode: the LAST matching pattern wins, so ask goes before deny; otherwise
    # "git push *" (ask) would override "git push --force *" (deny).
    if (OPENCODE_DIR / "opencode.jsonc").exists():
        sys.exit("sync-guardrails: ~/.config/opencode/opencode.jsonc exists; comments can't be "
                 "preserved, so it is not rewritten. Move its settings to opencode.json first.")
    new = {f"{c}{s}": decision
           for decision, commands in (("ask", policy["ask"]), ("deny", policy["deny"]))
           for c in commands for s in ("", " *")}
    config = load_json(OPENCODE, {"$schema": "https://opencode.ai/config.json"})
    permission = config.setdefault("permission", {})
    bash = permission.get("bash", {})
    if isinstance(bash, str):
        bash = {"*": bash}
    previous = state.get("opencode", [])
    bash = {k: v for k, v in bash.items() if k not in previous and k not in new}
    bash.update(new)
    permission["bash"] = bash
    write_json(OPENCODE, config)
    state["opencode"] = list(new)


def main() -> None:
    policy = yaml.safe_load(POLICY.read_text())
    policy = {key: policy.get(key) or [] for key in ("deny", "ask", "deny_read")}
    state = load_json(STATE, {})
    synced, skipped = [], []
    for name, directory, sync in (
        ("Claude Code", CLAUDE_DIR, lambda: sync_claude(policy, state)),
        ("Codex", CODEX_DIR, lambda: sync_codex(policy)),
        ("OpenCode", OPENCODE_DIR, lambda: sync_opencode(policy, state)),
    ):
        if directory.is_dir():
            sync()
            synced.append(name)
        else:
            skipped.append(name)
    write_json(STATE, state)
    print(f"Synced {len(policy['deny'])} deny / {len(policy['ask'])} ask rules to: "
          f"{', '.join(synced) or 'nothing'}."
          + (f" Skipped (not installed): {', '.join(skipped)}." if skipped else ""))


if __name__ == "__main__":
    main()
